public class AmplemarketMapping {
    @AuraEnabled public Id id;
    @AuraEnabled public String objectApiName;
    @AuraEnabled public String mappingType;
    @AuraEnabled public String amplemarketField;
    @AuraEnabled public String salesforceField;
    @AuraEnabled public Boolean revealEmail;
    @AuraEnabled public Boolean revealPhone;
    @AuraEnabled public String updateBehavior;
    @AuraEnabled public Boolean isActive;
}
